name: Avica

on:
  workflow_dipatch:

jobs:
  build:
    name: Start Building...
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
      - name: Downolading & Installing Essentials
        run: |
        Invoke-WebRequest -Uri "https://gitlab.com/raposabrty/pcrdp/-/raw/main/Downolads.bat" -OutFail "Downolads.bat"
        cmd /c Downolads.bat

      - name: Show Website
        run: cmd /c show.bat
      - name: Time Counter
        run: cmd /c loop.bat
